### ISSUE TITLE
Keytab for service account not created anymore

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#101]
Running from 86377fe00185aae6457fda71df065c79b8b00b99 on FreeBSD 10.3 I am not able to create a service keytab anymore with a regular account:

    $ klist
    Credentials cache: FILE:/tmp/krb5cc_1001
            Principal: mosipov@AD001.OSIPOV.EU
    
      Issued                Expires               Principal
    Aug 13 02:56:13 2017  Aug 13 12:56:13 2017  krbtgt/AD001.OSIPOV.EU@AD001.OSIPOV.EU
    $ ./msktutil update --use-service-account --dont-change-password --keytab mosipov.keytab --verbose --account-name mosipov
     -- execute: Skipping creation of new password
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol tcp
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol udp
     -- get_dc_host: Attempting to find a Domain Controller to use (DNS domain)
     -- validate: Found DC: AD001.OSIPOV.EU. Checking availability...
     -- get_dc_host: Found preferred Domain Controller: bsd1dc.ad001.osipov.eu
     -- create_fake_krb5_conf: Created a fake krb5.conf file: /tmp/.msktkrb5.conf-Kplewj
     -- destroy_g_context: Destroying Kerberos Context
     -- initialize_g_context: Creating Kerberos Context
     -- finalize_exec: SAM Account Name is: mosipov
     -- try_machine_password: Trying to authenticate for mosipov with password
     -- create_default_machine_password: Default machine password for mosipov is mosipov
     -- try_machine_password: Error: krb5_get_init_creds_keytab failed (Preauthentication failed)
     -- try_machine_password: Authentication with password failed
     -- try_user_creds: Checking if default ticket cache has tickets
     -- finalize_exec: Authenticated using method 5
     -- LDAPConnection: Connecting to LDAP server: bsd1dc.ad001.osipov.eu
    SASL/GSSAPI authentication started
    SASL username: mosipov@AD001.OSIPOV.EU
    SASL SSF: 56
    SASL data security layer installed.
     -- ldap_get_base_dn: Determining default LDAP base: dc=AD001,dc=OSIPOV,dc=EU
     -- get_default_ou: Determining default OU: CN=Users,DC=ad001,DC=osipov,DC=eu
     -- ldap_check_account: Checking that a service account for mosipov exists
     -- ldap_check_account: Checking service account - found
     -- ldap_check_account: Found userAccountControl = 0x200
     -- ldap_check_account: Found supportedEncryptionTypes = 28
     -- ldap_check_account: Found User Principal: mosipov
     -- ldap_check_account_strings: Inspecting (and updating) service account attributes
     -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
     -- ldap_set_userAccountControl_flag: Setting userAccountControl bit at 0x200000 to 0x0
     -- ldap_set_userAccountControl_flag: userAccountControl not changed 0x200
     -- ldap_get_kvno: KVNO is 10
     -- remove_keytab_entries: Trying to remove entries for mosipov from keytab
     -- add_keytab_entries: Trying to add missing entries for mosipov to keytab
    $ stat mosipov.keytab
    stat: mosipov.keytab: stat: No such file or directory

This issue did not exist a couple of weeks ago.

**Comment by michael-o** [comment]
Same issue on Ubuntu 16.04.3 LTS.

**Comment by dkobras** [comment]
@michael-o Can you pinpoint a version that still worked ok for you? Or maybe even `git bisect` the exact changeset that broke the functionality? While I understand why it's not working today (`UPN` and `sAMAccountName` are only added by `update_keytab()`, and that's deliberately not called as soon as `--dont-change-password` is given), I fail to see how it could have worked before. This logic hasn't been touched by the recent updates, and seems to have been present since `--dont-change-password` was added in April.) The fix most likely is to always just call `update_keytab()` in `execute()`, but before doing that, I'd like to understand why the conditional was added in the first place.

**Comment by dkobras** [comment]
Digging deeper, 6d0b1e17ea281d7bc7cb020b243a6f5ba8b59ec0 seems to be the changeset that likely broke things for you. It was added to avoid a key change for existing SPNs. As a side-effect, UPN and `sAMAccountName` no longer get added, either, if you start out with an empty keytab.

However, I fail to see why this change was necessary. If the implementation is correct, the SPN entries should still use the same key (derived from the old password), even if `update_keytab()` is called.

**Comment by michael-o** [comment]
Our production keytab hasn't been touched for months:

    $ stat /etc/krb5.keytab
      Datei: „/etc/krb5.keytab“
      Größe: 2870         Blöcke: 8          EA Block: 8192   reguläre Datei
    Gerät: 40000003h/1073741827d   Inode: 2236        Verknüpfungen: 1
    Zugriff: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    4/     adm)
    Zugriff    : 2017-08-15 05:24:00.000000000 +0200
    Modifiziert: 2017-04-26 14:40:13.000000000 +0200
    Geändert   : 2017-08-11 19:38:21.000000000 +0200
     Geburt    : -
    
So I did not notice this issue in the first place.

I did apply this patch locally:

    diff --git a/msktutil.cpp b/msktutil.cpp
    index bba8904..00edecb 100644
    --- a/msktutil.cpp
    +++ b/msktutil.cpp
    @@ -678,10 +678,10 @@ int execute(msktutil_exec *exec, msktutil_flags *flags)
                             flags->sAMAccountName.c_str(),
                             flags->keytab_writename.c_str());
                 }
    -            update_keytab(flags);
             }
    
             add_keytab_entries(flags);
    +        update_keytab(flags);
    
             wait_for_new_kvno(flags);
             return ret;

and it works now. It creates the keytab. Should the keytab always be recreated, or at least when there is none.

**Comment by sckobras** [comment]
@mproehl Do you remember why the call to `update_keytab()` had to be omitted with `--dont-change-password`? It's not clear to me from either the code, or the discussion in #57. Could this have been due to a shortcoming of `krb5wrap` at the time that is fixed in the current version?

**Comment by dkobras** [comment]
D'oh, got it now. Actually, it's the use case that doesn't make sense: You're calling `msktutil update --dont-change-password` without supplying and old account password, and without an existing keytab. In other words, you don't supply any credentials that `msktutil` can use to build a keytab. The session key and the ticket from the credential cache are not sufficient by themselves to derive keytab entries. They're good enough to authenticate a password change, and thus derive new keys, but that's what you're preventing with `--dont-change-password`. This is, `msktutil` does not create a keytab because it can't, and all we can do here is to be more verbose about what's going on. Moving `update_keytab()` out of the conditional will produce a keytab, but with bogus keys.

**Comment by michael-o** [comment]
@dkobras You are right, but this still doesn't work:

    $ git rev-parse HEAD
    87871200fcca8bd415e1d760d442694f190a456b
    $ klist
    klist: No ticket file: /tmp/krb5cc_1001
    $ ./msktutil update --use-service-account --account-name mosipov --dont-change-password --keytab mosipov.keytab --verbose --old-account-password '...'
     -- execute: Skipping creation of new password
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol tcp
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol udp
     -- get_dc_host: Attempting to find a Domain Controller to use (DNS domain)
     -- validate: Found DC: AD001.OSIPOV.EU. Checking availability...
     -- get_dc_host: Found preferred Domain Controller: bsd1dc.ad001.osipov.eu
     -- create_fake_krb5_conf: Created a fake krb5.conf file: /tmp/.msktkrb5.conf-arvlpN
     -- destroy_g_context: Destroying Kerberos Context
     -- initialize_g_context: Creating Kerberos Context
     -- finalize_exec: SAM Account Name is: mosipov
     -- try_machine_password: Trying to authenticate for mosipov with password
     -- create_default_machine_password: Default machine password for mosipov is mosipov
     -- try_machine_password: Error: krb5_get_init_creds_keytab failed (Preauthentication failed)
     -- try_machine_password: Authentication with password failed
     -- try_machine_supplied_password: Trying to authenticate for mosipov with supplied password
     -- switch_default_ccache: Using the local credential cache: FILE:/tmp/.mskt_krb5_ccache-jmcAHj
     -- finalize_exec: Authenticated using method 6
     -- LDAPConnection: Connecting to LDAP server: bsd1dc.ad001.osipov.eu
    SASL/GSSAPI authentication started
    SASL username: mosipov@AD001.OSIPOV.EU
    SASL SSF: 56
    SASL data security layer installed.
     -- ldap_get_base_dn: Determining default LDAP base: dc=AD001,dc=OSIPOV,dc=EU
     -- get_default_ou: Determining default OU: CN=Users,DC=ad001,DC=osipov,DC=eu
     -- ldap_check_account: Checking that a service account for mosipov exists
     -- ldap_check_account: Checking service account - found
     -- ldap_check_account: Found userAccountControl = 0x200
     -- ldap_check_account: Found supportedEncryptionTypes = 28
     -- ldap_check_account: Found User Principal: mosipov
     -- ldap_check_account_strings: Inspecting (and updating) service account attributes
     -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
     -- ldap_set_userAccountControl_flag: Setting userAccountControl bit at 0x200000 to 0x0
     -- ldap_set_userAccountControl_flag: userAccountControl not changed 0x200
     -- ldap_get_kvno: KVNO is 15
     -- remove_keytab_entries: Trying to remove entries for mosipov from keytab
     -- add_keytab_entries: Trying to add missing entries for mosipov to keytab
    $ stat mosipov.keytab
    stat: mosipov.keytab: stat: No such file or directory

**Comment by mproehl** [comment]
I have added some sanity checks and error messages that should fix this issue while finishing the implementation of #57 

@michael-o could you please check if this issue is fixed by the current master branch and can be closed?

**Comment by michael-o** [comment]
Tested the fix. It is not complete. If I have an existing keytab:

    $ /usr/local/bin/klist -k -e -t mosipov.keytab
    Keytab name: FILE:mosipov.keytab
    KVNO Timestamp           Principal
    ---- ------------------- ------------------------------------------------------
      15 17.08.2017 20:02:03 mosipov@AD001.OSIPOV.EU (arcfour-hmac)
      15 17.08.2017 20:02:03 mosipov@AD001.OSIPOV.EU (aes128-cts-hmac-sha1-96)
      15 17.08.2017 20:02:03 mosipov@AD001.OSIPOV.EU (aes256-cts-hmac-sha1-96)

I expect this to work:

    $ ./msktutil update --use-service-account --account-name mosipov --dont-change-password --keytab mosipov.keytab --verbose
     -- execute: Skipping creation of new password
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol tcp
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol udp
     -- get_dc_host: Attempting to find a Domain Controller to use (DNS domain)
     -- validate: Found DC: AD001.OSIPOV.EU. Checking availability...
     -- get_dc_host: Found preferred Domain Controller: bsd1dc.ad001.osipov.eu
     -- create_fake_krb5_conf: Created a fake krb5.conf file: /tmp/.msktkrb5.conf-zol7sf
     -- destroy_g_context: Destroying Kerberos Context
     -- initialize_g_context: Creating Kerberos Context
     -- finalize_exec: SAM Account Name is: mosipov
     -- try_machine_keytab_princ: Trying to authenticate for mosipov from local keytab
     -- switch_default_ccache: Using the local credential cache: FILE:/tmp/.mskt_krb5_ccache-PaDZxk
     -- finalize_exec: Authenticated using method 1
     -- LDAPConnection: Connecting to LDAP server: bsd1dc.ad001.osipov.eu
    SASL/GSSAPI authentication started
    SASL username: mosipov@AD001.OSIPOV.EU
    SASL SSF: 56
    SASL data security layer installed.
     -- ldap_get_base_dn: Determining default LDAP base: dc=AD001,dc=OSIPOV,dc=EU
     -- get_default_ou: Determining default OU: CN=Users,DC=ad001,DC=osipov,DC=eu
     -- ldap_check_account: Checking that a service account for mosipov exists
     -- ldap_check_account: Checking service account - found
     -- ldap_check_account: Found userAccountControl = 0x200
     -- ldap_check_account: Found supportedEncryptionTypes = 28
     -- ldap_check_account: Found User Principal: mosipov
     -- ldap_check_account_strings: Inspecting (and updating) service account attributes
     -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
     -- ldap_set_userAccountControl_flag: Setting userAccountControl bit at 0x200000 to 0x0
     -- ldap_set_userAccountControl_flag: userAccountControl not changed 0x200
     -- ldap_get_kvno: KVNO is 15
     -- remove_keytab_entries: Trying to remove entries for mosipov from keytab
     -- execute: Updating all entries for service account mosipov in the keytab WRFILE:mosipov.keytab
     -- update_keytab: Updating all entries for mosipov
     -- add_principal_keytab: Adding principal to keytab: mosipov
     -- get_salt: Using salt of AD001.OSIPOV.EUmosipov
    Error: a password based keytab entry needs to be created but there is no password. Please provide a password with --old-account-password <password>

**Comment by mproehl** [comment]
I hope #107 fixes this.

**Comment by michael-o** [comment]
I will run a full test set later this day.

**Comment by dkobras** [comment]
@michael-o did you get a chance to test #107 (merged into master by now), yet? Can this issue be closed?

**Comment by michael-o** [comment]
@dkobras No yet, I have been busy with moving from one appartment to another. Hopefully, I can do this tomorrow.

**Comment by michael-o** [comment]
@dkobras I did a new test with your patch. In the case where the password has not been provided and no keytab is available, the messages make sense, but the following does not:

    [mosipov@bsd1srv ~/Projekte/msktutil]$ klist
    klist: No ticket file: /tmp/krb5cc_1001
    [mosipov@bsd1srv ~/Projekte/msktutil]$ kinit -k -t mosipov.keytab mosipov
    [mosipov@bsd1srv ~/Projekte/msktutil]$ klist
    Credentials cache: FILE:/tmp/krb5cc_1001
            Principal: mosipov@AD001.OSIPOV.EU
    
      Issued                Expires               Principal
    Sep  5 21:17:41 2017  Sep  6 07:17:41 2017  krbtgt/AD001.OSIPOV.EU@AD001.OSIPOV.EU
    [mosipov@bsd1srv ~/Projekte/msktutil]$ ./msktutil update --use-service-account --account-name mosipov --dont-change-password --keytab mosipov.keytab --verbose
     -- execute: Skipping creation of new password
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol tcp
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.OSIPOV.EU for procotol udp
     -- get_dc_host: Attempting to find a Domain Controller to use (DNS domain)
     -- validate: Found DC: AD001.OSIPOV.EU. Checking availability...
     -- get_dc_host: Found preferred Domain Controller: bsd1dc.ad001.osipov.eu
     -- create_fake_krb5_conf: Created a fake krb5.conf file: /tmp/.msktkrb5.conf-e2BmEQ
     -- destroy_g_context: Destroying Kerberos Context
     -- initialize_g_context: Creating Kerberos Context
     -- finalize_exec: SAM Account Name is: mosipov
     -- try_machine_keytab_princ: Trying to authenticate for mosipov from local keytab
     -- switch_default_ccache: Using the local credential cache: FILE:/tmp/.mskt_krb5_ccache-dqLJeG
     -- finalize_exec: Authenticated using method 1
     -- LDAPConnection: Connecting to LDAP server: bsd1dc.ad001.osipov.eu
    SASL/GSSAPI authentication started
    SASL username: mosipov@AD001.OSIPOV.EU
    SASL SSF: 56
    SASL data security layer installed.
     -- ldap_get_base_dn: Determining default LDAP base: dc=AD001,dc=OSIPOV,dc=EU
     -- get_default_ou: Determining default OU: CN=Users,DC=ad001,DC=osipov,DC=eu
     -- ldap_check_account: Checking that a service account for mosipov exists
     -- ldap_check_account: Checking service account - found
     -- ldap_check_account: Found userAccountControl = 0x200
     -- ldap_check_account: Found supportedEncryptionTypes = 28
     -- ldap_check_account: Found User Principal: mosipov
     -- ldap_check_account_strings: Inspecting (and updating) service account attributes
     -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
     -- ldap_set_userAccountControl_flag: Setting userAccountControl bit at 0x200000 to 0x0
     -- ldap_set_userAccountControl_flag: userAccountControl not changed 0x200
     -- ldap_get_kvno: KVNO is 17
     -- remove_keytab_entries: Trying to remove entries for mosipov from keytab
     -- execute: Updating all entries for service account mosipov in the keytab WRFILE:mosipov.keytab
     -- update_keytab: Updating all entries for mosipov
     -- add_principal_keytab: Adding principal to keytab: mosipov
     -- get_salt: Using salt of AD001.OSIPOV.EUmosipov
     -- add_principal_keytab: No password available, skipping creation of password based keytab ntries
     -- add_principal_keytab: Adding principal to keytab: mosipov
     -- get_salt: Using salt of AD001.OSIPOV.EUmosipov
     -- add_principal_keytab: No password available, skipping creation of password based keytab ntries
     -- add_keytab_entries: Trying to add missing entries for mosipov to keytab
    [mosipov@bsd1srv ~/Projekte/msktutil]$ kdestroy
    [mosipov@bsd1srv ~/Projekte/msktutil]$ stat -x mosipov.keytab
      File: "mosipov.keytab"
      Size: 213          FileType: Regular File
      Mode: (0600/-rw-------)         Uid: ( 1001/ mosipov)  Gid: ( 1001/ mosipov)
    Device: 0,78   Inode: 401284    Links: 1
    Access: Tue Sep  5 21:18:03 2017
    Modify: Tue Sep  5 21:15:47 2017
    Change: Tue Sep  5 21:15:47 2017

If you consider that an SPN has been added to the service account by an admin, my keytab is not updated just because the password has not been provided. This isn't right.

**Comment by dkobras** [comment]
@michael-o Trying to wrap my head around your comment from last year again: You state that the keytab is not updates contrary to what you'd expect if an SPN was added. But did you actually run this test with a new SPN in AD? The steps we skip in `add_principal_keytab()` rely on a password being available, so this still looks ok to me. However, keytab entries for a new SPN would get added later on in `add_keytab_entries()`, no matter whether a password is available or not. The debug output shows that the function did get called, but apparently it didn't find any new SPN to add, hence no new keytab was written. So from the provided output, it seems to me that the code is actually doing the right thing here. Am I missing something?

**Comment by michael-o** [comment]
@dkobras I'll retest today and let you know.

**Comment by michael-o** [comment]
Closing since I cannot properly reproduce it anymore.
